# Schema for the configuration files of the uc_helcim module.

uc_helcim.settings:
  type: config_object
  label: 'Credit card configuration settings'
  mapping:
    encryption_path:
      type: string
      label: 'Internal path to encryption keys'
    visa:
      type: boolean
      label: 'Accept Visa?'
    mastercard:
      type: boolean
      label: 'Accept MasterCard?'
    discover:
      type: boolean
      label: 'Accept Discover?'
    amex:
      type: boolean
      label: 'Accept American Express?'

payment_method.settings.helcim_gateway:
  type: mapping
  label: 'Helcim gateway plugin configuration settings'
  mapping:
    txn_type:
      type: integer
      label: 'Transaction type code'
    debug:
      type: boolean
      label: 'Flag to log debug output'
